name: native_widgets
description: A new Flutter package for using Android and iOS natively on each platform.
version: 1.3.7+1
author: Rhodes Davis Jr. <rody.davis.jr@gmail.com>
homepage: https://github.com/fluttercommunity/native_widgets
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: ^0.4.0
  uuid: ^2.0.4
  intl: ^0.16.1
  flutter_list_drag_and_drop: ^0.1.6
  flutter_slidable: ^0.5.4
  flutter_platform_widgets: ^0.32.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   flutter_sticky_header:
#     git: https://github.com/rodydavis/flutter_sticky_header

flutter:
